# Generated by Django 4.2.7 on 2025-10-11 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Edad')),
                ('civil_status', models.CharField(help_text='Soltero/a, Casado/a, Divorciado/a, Viudo/a, Unión libre', max_length=50, verbose_name='Estado civil')),
                ('profession', models.CharField(max_length=100, verbose_name='Profesión')),
                ('address', models.TextField(verbose_name='Dirección de domicilio')),
                ('home_phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono de casa')),
                ('cell_phone', models.CharField(max_length=15, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('housing_ownership', models.CharField(choices=[('Propia', 'Propia'), ('Alquilada', 'Alquilada')], max_length=20, verbose_name='¿Es casa propia o alquilada?')),
                ('landlord_permission', models.BooleanField(blank=True, help_text='Solo aplicable si la vivienda es alquilada', null=True, verbose_name='¿El dueño está de acuerdo con mascotas?')),
                ('dwelling_type', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Finca', 'Finca'), ('Granja', 'Granja')], max_length=20, verbose_name='Tipo de vivienda')),
                ('adoption_reason', models.TextField(verbose_name='¿Por qué desea adoptar? Explique')),
                ('pet_location_in_home', models.CharField(help_text='Ej: Patio, Jardín, Terraza, Toda la casa', max_length=100, verbose_name='¿En dónde se mantendrá la mascota?')),
                ('adults_in_home', models.PositiveIntegerField(verbose_name='¿Cuántos adultos viven en casa?')),
                ('children_in_home', models.PositiveIntegerField(default=0, verbose_name='¿Cuántos niños viven en casa?')),
                ('all_family_agrees', models.BooleanField(verbose_name='¿Todos aman a los animales y están de acuerdo?')),
                ('can_afford_pet', models.BooleanField(verbose_name='¿Tiene economía para alimentación, veterinario y gastos futuros?')),
                ('has_had_pets_before', models.BooleanField(verbose_name='¿Alguna vez ha tenido mascota?')),
                ('previous_pet_experience', models.TextField(blank=True, help_text='Describa su experiencia previa con mascotas', verbose_name='¿Cuáles? ¿Qué les sucedió?')),
                ('has_current_pets', models.BooleanField(verbose_name='¿Tiene mascotas actualmente?')),
                ('current_pets_info', models.TextField(blank=True, help_text='¿Cuántas y cuáles mascotas tiene?', verbose_name='Información de mascotas actuales')),
                ('adoption_purpose', models.CharField(choices=[('Para hogar', 'Para hogar'), ('Para guardianía', 'Para guardianía')], max_length=20, verbose_name='¿Para hogar o guardianía?')),
                ('aware_of_potential_damage', models.BooleanField(verbose_name='¿Consciente de que puede dañar adornos?')),
                ('damage_plan', models.TextField(verbose_name='¿Qué haría ante posibles daños?')),
                ('willing_to_educate', models.BooleanField(verbose_name='¿Dispuesto a comprender y educar a la mascota?')),
                ('behavior_plan', models.TextField(verbose_name='¿Qué medidas tomaría si el comportamiento no es el esperado?')),
                ('agrees_to_home_visits', models.BooleanField(verbose_name='¿Acepta visitas periódicas al domicilio?')),
                ('home_visit_reasoning', models.TextField(blank=True, help_text='Explique por qué acepta o no las visitas', verbose_name='¿Por qué?')),
                ('understands_no_transfer_policy', models.BooleanField(verbose_name='¿Comprende que no puede entregar a terceros?')),
                ('vision_in_5_years', models.TextField(verbose_name='¿Cómo se ve con su adoptado en 5 años?')),
                ('agrees_to_sterilize', models.BooleanField(verbose_name='¿Se compromete a esterilizar cuando tenga edad?')),
                ('dpi_copy', models.FileField(help_text='Documento de identificación personal', upload_to='adoptions/dpi/', verbose_name='Copia de DPI')),
                ('utility_bill_copy', models.FileField(help_text='Comprobante de domicilio', upload_to='adoptions/bills/', verbose_name='Recibo de luz o teléfono')),
                ('application_status', models.CharField(choices=[('Recibida', 'Recibida'), ('En Revisión', 'En Revisión'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Recibida', max_length=20, verbose_name='Estado de la solicitud')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
            ],
            options={
                'verbose_name': 'Solicitud de adopción',
                'verbose_name_plural': 'Solicitudes de adopción',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('relationship', models.CharField(max_length=50, verbose_name='Parentesco o relación')),
            ],
            options={
                'verbose_name': 'Referencia personal',
                'verbose_name_plural': 'Referencias personales',
            },
        ),
        migrations.CreateModel(
            name='SimplifiedAdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre y apellido completo')),
                ('pet_name_requested', models.CharField(help_text='Nombre de la mascota que desea adoptar', max_length=100, verbose_name='Nombre del perrito solicitado')),
                ('phone', models.CharField(max_length=15, verbose_name='Número de teléfono (WhatsApp)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('filled_form_pdf', models.FileField(help_text='Descargue el formulario, llénelo, fírmelo y súbalo escaneado', upload_to='adoptions/simplified_forms/', verbose_name='Formulario de adopción completado y firmado (PDF)')),
                ('status', models.CharField(choices=[('Recibida', 'Recibida'), ('En Revisión', 'En Revisión'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Recibida', max_length=20, verbose_name='Estado de la solicitud')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplified_applications', to='pets.pet', verbose_name='Mascota a adoptar')),
            ],
            options={
                'verbose_name': 'Solicitud Simplificada de Adopción',
                'verbose_name_plural': 'Solicitudes Simplificadas de Adopción',
                'ordering': ['-created_at'],
            },
        ),
    ]
