# Generated by Django 4.2.7 on 2025-10-11 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplifiedadoptionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simplified_applications_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AddField(
            model_name='personalreference',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='adoptions.adoptionapplication', verbose_name='Solicitud de adopción'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to='pets.pet', verbose_name='Mascota a adoptar'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
    ]
