# Generated by Django 4.2.7 on 2025-10-11 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('question', models.CharField(max_length=200, verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('category', models.CharField(choices=[('adoption', 'Adopción'), ('care', 'Cuidados'), ('donation', 'Donaciones'), ('volunteer', 'Voluntariado'), ('general', 'General')], max_length=50, verbose_name='Categoría')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pregunta frecuente',
                'verbose_name_plural': 'Preguntas frecuentes',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('pet_name', models.CharField(max_length=100, verbose_name='Nombre de la mascota')),
                ('adopter_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del adoptante')),
                ('story', models.TextField(verbose_name='Historia')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='success_stories/before/', verbose_name='Imagen anterior')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='success_stories/after/', verbose_name='Imagen actual')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Historia destacada')),
            ],
            options={
                'verbose_name': 'Historia de éxito',
                'verbose_name_plural': 'Historias de éxito',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='URL amigable')),
                ('summary', models.TextField(max_length=300, verbose_name='Resumen')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imagen destacada')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Artículo destacado')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Artículo de noticias',
                'verbose_name_plural': 'Artículos de noticias',
                'ordering': ['-published_date'],
            },
        ),
    ]
