# Generated by Django 4.2.7 on 2025-10-11 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('subject', models.CharField(choices=[('general', 'Consulta general'), ('volunteer', 'Quiero ser voluntario'), ('donation', 'Donaciones'), ('found_pet', 'Encontré una mascota'), ('lost_pet', 'Perdí mi mascota'), ('other', 'Otro')], max_length=20, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('in_progress', 'En proceso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='new', max_length=15, verbose_name='Estado')),
                ('admin_response', models.TextField(blank=True, verbose_name='Respuesta del administrador')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
