# Generated by Django 4.2.7 on 2025-10-11 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('street', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(default='Ciudad de Guatemala', max_length=100, verbose_name='Ciudad')),
                ('department', models.CharField(default='Guatemala', max_length=100, verbose_name='Departamento')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('country', models.CharField(default='Guatemala', max_length=50, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Formato: '+50212345678' o '12345678'", regex='^\\+?502?[0-9]{8}$')], verbose_name='Número de teléfono')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Teléfono principal')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Huellitas', max_length=100, verbose_name='Nombre del sitio')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(max_length=15, verbose_name='Teléfono de contacto')),
                ('about_us', models.TextField(blank=True, verbose_name='Acerca de nosotros')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.address', verbose_name='Dirección principal')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuraciones del sitio',
            },
        ),
    ]
