# Generated by Django 4.2.7 on 2025-10-11 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('species', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('other', 'Otro')], default='dog', max_length=20, verbose_name='Especie')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('gender', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1, verbose_name='Sexo')),
                ('age_years', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Edad (años)')),
                ('age_months', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Edad (meses)')),
                ('size', models.CharField(choices=[('small', 'Pequeño'), ('medium', 'Mediano'), ('large', 'Grande'), ('extra_large', 'Extra Grande')], max_length=20, verbose_name='Tamaño')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Color')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('adopted', 'Adoptado'), ('in_process', 'En proceso de adopción'), ('not_available', 'No disponible')], default='available', max_length=20, verbose_name='Estado')),
                ('is_sterilized', models.BooleanField(default=False, verbose_name='Castrado/Esterilizado')),
                ('is_vaccinated', models.BooleanField(default=False, verbose_name='Vacunado')),
                ('is_dewormed', models.BooleanField(default=False, verbose_name='Desparasitado')),
                ('description', models.TextField(blank=True, help_text='Descripción corta sobre la mascota', verbose_name='Sobre mí')),
                ('characteristics', models.TextField(blank=True, help_text='Temperamento, personalidad, necesidades especiales, etc.', verbose_name='Características especiales')),
                ('special_needs', models.TextField(blank=True, verbose_name='Necesidades especiales')),
                ('friendly_with_kids', models.BooleanField(default=False, verbose_name='Amigable con niños')),
                ('adapts_to_indoor_living', models.BooleanField(default=True, verbose_name='Se adapta a vivir dentro de casa')),
                ('easy_to_train', models.BooleanField(default=False, verbose_name='Fácil de entrenar')),
                ('energy_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], default='medium', max_length=10, verbose_name='Nivel de energía')),
                ('arrival_date', models.DateField(auto_now_add=True, verbose_name='Fecha de llegada')),
                ('adoption_date', models.DateField(blank=True, null=True, verbose_name='Fecha de adopción')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='pets/main/', verbose_name='Imagen principal')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('image', models.ImageField(upload_to='pets/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Imagen de mascota',
                'verbose_name_plural': 'Imágenes de mascotas',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
